# Generated by Django 4.2.4 on 2023-09-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(default='default', max_length=100)),
                ('content', models.CharField(default='RNBQKBNRPPPPPPPP                                pppppppprnbqkbnr', max_length=64)),
                ('whites_turn', models.BooleanField(default=True)),
                ('checkmate', models.BooleanField(default=False)),
                ('left_white_rook_moved', models.BooleanField(default=False)),
                ('right_white_rook_moved', models.BooleanField(default=False)),
                ('white_king_moved', models.BooleanField(default=False)),
                ('left_black_rook_moved', models.BooleanField(default=False)),
                ('right_black_rook_moved', models.BooleanField(default=False)),
                ('black_king_moved', models.BooleanField(default=False)),
            ],
        ),
    ]
