# Generated by Django 4.2.1 on 2023-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=('RNBKQBNR', 'PPPPPPPP', '                                ', 'pppppppp', 'rnbkqbnr'), max_length=64)),
                ('whites_turn', models.BooleanField(default=True)),
            ],
        ),
    ]
