# Generated by Django 4.2.1 on 2023-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.CharField(default='RNBKQBNRPPPPPPPP                                pppppppprnbkqbnr', max_length=64),
        ),
    ]
